#
# AntiHaxerman Config File
# by Tecnio
#

alerts:
  format: "&cAntiHaxerman &8> &c%player%&8 has failed &c%check% &8(&cType %type%&8) VL: &c%vl%"
  log-to-console: false

checks:
  aim:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  angle:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  aura:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  autoblock:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  autoclicker:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  badpackets:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  fastclimb:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  flight:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  inventory:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  invmove:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  largemove:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  motion:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  nofall:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  noslowdown:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  omnisprint:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  pingspoof:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  post:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  reach:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  speed:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  timer:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage
  velocity:
    enabled: true
    punish-commands:
      - ban %player% Unfair Advantage